# What is NumPy Array
- A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers.
- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently 
- NumPy is much faster compare to Python list.

# Difference between NumPy array and Python List

In [3]:
#python list
%timeit [i**2 for i in range(1,4)]

1.15 µs ± 87.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [4]:
#NumPy array
import numpy as np
%timeit np.arange(1,4)**2


1.12 µs ± 173 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [5]:
#Big size python list
%timeit [i**2 for i in range(1,10000)]

2.88 ms ± 58.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
#NumPy array
%timeit np.arange(1,10000)**2

13 µs ± 157 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# NumPy array

In [2]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
arr.size

4

In [5]:
arr.ndim

1

In [7]:
arr.shape

(4,)

# reshape() function

In [7]:
arr=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10]).reshape(2,-1)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [3]:
arr1=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,-1)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
#creation of 3D array
arr=np.array([1,2,3,4,5,6,7,8]).reshape(2,2,2)
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# zeros(), #ones(), #eye(), #diag() function

In [15]:
a=np.zeros(4)
a

array([0., 0., 0., 0.])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# randint() and rand() function

In [4]:
np.random.randint(1,10,4)

array([6, 8, 3, 5])

In [23]:
np.random.rand(5)

array([0.45189259, 0.60745756, 0.27090789, 0.07498018, 0.00314075])

In [24]:
np.random.rand(5)


array([0.21468706, 0.14350358, 0.38186672, 0.60530843, 0.20204465])

In [16]:
arr=np.random.randint(1,111,10).reshape(2,5)
arr

array([[ 2, 83,  5, 91, 44],
       [25, 87, 53, 62, 98]])

In [4]:
arr=np.random.randint(1,111,20)
arr

array([  2,  37,   7, 100,  77,  99,  43, 104,  58,  96,  25, 101,  40,
        65,  88,  22,  44,  17, 107,  46])

# Indexing and Slicing of NumPy array

In [6]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [7]:
arr[1:]

array([2, 3, 4, 5])

In [21]:
arr[-1:]

array([5])

In [22]:
arr[-3:]

array([3, 4, 5])

In [23]:
arr[1:4]# 4 is excluded

array([2, 3, 4])

In [19]:
arr[0:5:2]

array([1, 3, 5])

In [26]:
#Reversing of an array
arr[::-1]

array([5, 4, 3, 2, 1])

In [27]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
#first 1D array
matrix[0]

array([1, 2, 3])

In [29]:
#second element of first 1D array
matrix[0][1]

2

In [30]:
matrix[1][1]

5

In [31]:
# Using only single Bracket
matrix[0,1]

2

In [32]:
matrix[1,1]

5

In [33]:
matrix[:2, :2]

array([[1, 2],
       [4, 5]])

In [34]:
matrix[1:,1:]

array([[5, 6],
       [8, 9]])

In [9]:
np.random.seed(123)
arr=np.random.randint(1,101,25).reshape(5,5)
arr

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [36]:
arr[1:4,1:4]


array([[87, 98, 97],
       [33, 47, 97],
       [79, 37, 97]])

In [37]:
arr[2:,2:]

array([[47, 97, 26],
       [37, 97, 81],
       [56, 68,  3]])

# view vs copy

In [48]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [50]:
sliced_array=arr[2:4]  
sliced_array

array([3, 4])

In [51]:
sliced_array[:]=0
sliced_array


array([0, 0])

In [52]:
arr # view reflect changes in original array

array([1, 2, 0, 0, 5])

In [53]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [54]:
sliced_array=arr[2:4].copy()
sliced_array

array([3, 4])

In [55]:
sliced_array[:]=0
sliced_array

array([0, 0])

In [56]:
arr #Copy does not reflect changes in original array

array([1, 2, 3, 4, 5])

# Conditinal selection

In [60]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10])

In [66]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

# NumPy axis
for rows put axis=1 and for columns put axis=0

In [20]:
arr=np.random.randint(1,10,9).reshape(3,3)
arr

array([[3, 3, 6],
       [7, 2, 6],
       [1, 1, 4]])

In [21]:
# calculate min element rowwise
np.min(arr,axis=1)

array([3, 2, 1])

In [22]:
# calcilate max element columnwise
np.max(arr, axis=0)

array([7, 3, 6])

# hstack() and vstack() function
these are used to concatinate two matrices horizontally and vertically

In [23]:
matrix1=np.random.randint(1,11,9).reshape(3,3)
matrix1

array([[9, 3, 4],
       [7, 4, 4],
       [1, 6, 1]])

In [24]:
matrix2=np.random.randint(50,100,9).reshape(3,3)
matrix2

array([[99, 59, 56],
       [75, 91, 85],
       [86, 52, 98]])

In [28]:
np.hstack((matrix1,matrix2))

array([[ 9,  3,  4, 99, 59, 56],
       [ 7,  4,  4, 75, 91, 85],
       [ 1,  6,  1, 86, 52, 98]])

In [27]:
np.vstack((matrix1,matrix2))

array([[ 9,  3,  4],
       [ 7,  4,  4],
       [ 1,  6,  1],
       [99, 59, 56],
       [75, 91, 85],
       [86, 52, 98]])